app:
  api:
    version: v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8001

spring:
  application:
    name: order-service

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: qa

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: uat

---
spring:
  config:
    activate:
      on-profile: prod
